### ISSUE TITLE
[Bug] Status Code 404: Task not created 

### ISSUE THREAD

**Issue by suyashdb** [Skyvern-AI/skyvern#1080]
All three containers are running correctly, however when i click on the task creation i get 404 error. no docker logs which talks about any error. 

![Screenshot 2024-10-28 at 8 49 12 PM](https://github.com/user-attachments/assets/61f15706-3392-47c9-85ce-a2884b102366)

**Comment by wintonzheng** [comment]
@suyashdb 

Are you running docker compose in a remote server?

If yes, what's your `environment` under the skyvern-ui  in your `docker-compose.yml`?

**Comment by suyashdb** [comment]
@wintonzheng 
here the env under skyvern-ui. Yes, i am running docker compose in a remote server. 

`
```
skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:v0.1.35
    restart: on-failure
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./.streamlit:/app/.streamlit
    environment:
      - VITE_WSS_BASE_URL=ws://localhost:8000/api/v1
    #   - VITE_API_BASE_URL=
    #   - VITE_SKYVERN_API_KEY=
    depends_on:
      skyvern:
        condition: service_healthy
        
```
